---
# tasks file for mongo
- name: Get mongodb-org GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927

- name: Copy sources list for mongodb-org (official MongoDB package repo)
  copy:
    src: mongodb-org-3.2.list
    dest: /etc/apt/sources.list.d
    mode: 0644

- name: Update the cache with the mongodb-org goodness
  apt:
    update_cache: yes

- name: Install mongo
  apt:
    name: mongodb-org=3.2.20
  notify:
    - Enable mongo

- name: Configure mongo service to run after cloud-config
  lineinfile:
    dest: /lib/systemd/system/mongod.service
    regexp: ^After=
    state: present
    line: After=network.target cloud-config.service

# Mongo docs recommend disabling --quiet flag in Production
# https://docs.mongodb.com/manual/reference/configuration-options/#systemLog.quiet
- name: Remove --quiet mongo command line option
  lineinfile:
    dest: /lib/systemd/system/mongod.service
    regexp: ^ExecStart=/usr/bin/mongod --quiet
    state: present
    line: ExecStart=/usr/bin/mongod --config /etc/mongod.conf

- name: Install pip
  apt:
    name: python-pip
    state: latest

# pymongo is needed for ansible mongodb_user module
- name: Install pymongo via pip
  pip:
    name: pymongo
    state: latest
