---
# tasks file for mongo
- name: Get mongodb-org GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927

- name: Copy sources list for mongodb-org (official MongoDB package repo)
  copy:
    src: mongodb-org-3.2.list
    dest: /etc/apt/sources.list.d
    mode: 0644

- name: Update the cache with the mongodb-org goodness
  apt:
    update_cache: yes

- name: Install mongo
  apt:
    name: mongodb-org=3.2.20
  notify:
    - Enable mongo

- name: Configure mongo service to run after cloud-config
  lineinfile:
    dest: /lib/systemd/system/mongod.service
    regexp: ^After=
    state: present
    line: After=network.target cloud-config.service

- name: Configure mongo service to use wired tiger
  lineinfile:
    dest: /etc/mongod.conf
    regexp: 'engine:'
    state: present
    line: '  engine: wiredTiger'

- name: Configure mongo service to listen on all interfaces
  blockinfile:
    path: /etc/mongod.conf
    block: |
      net:
        port: 27017
      # bindIp: 127.0.0.1
      # ssl:
      #   mode: disabled
      # http:
      #   enabled: true
      #   RESTInterfaceEnabled: true

- name: Install pip
  apt:
    name: python-pip
    state: latest

# pymongo is needed for ansible mongodb_user module
- name: Install pymongo via pip
  pip:
    name: pymongo
    state: latest
