---
# tasks file for mongo
- name: Get mongodb-org GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

- name: Copy sources list for mongodb-org (official MongoDB package repo)
  copy:
    src: mongodb-org-3.6.list
    dest: /etc/apt/sources.list.d
    mode: 0644

- name: Update the cache with the mongodb-org goodness
  package:
    update_cache: yes

- name: Install mongo
  package:
    name: mongodb-org=3.6.8
  notify:
    - Enable mongo

- name: Configure mongo service to run after cloud-config
  lineinfile:
    dest: /lib/systemd/system/mongod.service
    regexp: ^After=
    state: present
    line: After=network.target cloud-config.service

# Mongo docs recommend running via numactl on NUMA hosts
# https://docs.mongodb.com/manual/administration/production-notes/#mongodb-and-numa-hardware
- name: Start mongod via numactl
  lineinfile:
    dest: /lib/systemd/system/mongod.service
    regexp: ^ExecStart=/usr/bin/mongod
    state: present
    line: ExecStart=/usr/bin/numactl --interleave=all /usr/bin/mongod --config /etc/mongod.conf

# pymongo is needed for ansible mongodb_user module
- name: Install pymongo via pip
  pip:
    name: pymongo
    state: latest
