---
# tasks file for github_oauth

- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml
  become: no

- name: Delete local copy of GitHub OAuth token
  local_action:
    module: file
    path: /tmp/github_oauth_token.yml
    state: absent
  become: no
