#cloud-config

mounts:
  # Add new mount to /etc/fstab, but don't automatically mount it.  We
  # must handle nested mounts in bootcmd section below
  - [ /dev/nvme1n1, /var/cyhy/reports/output, xfs, 'defaults,noauto', '0', '2' ]

bootcmd:
  # Wait for EBS disks to be attached
  - 'while [ `lsblk | grep -c " disk"` -lt 2 ]; do echo Waiting for disks to attach...; sleep 5; done'
  # Format filesystem on each EBS volume (if one was not already there)
  # fs_setup does not honor the overwrite argument.  Always in full-cowboy mode. (v0.7.9)
  - 'blkid -c /dev/null /dev/nvme1n1 || mkfs.xfs /dev/nvme1n1 -L report_data'
  # Mount report volumes and set ownership.  Due to funky timing of
  # mounts vs. bootcmd, we have to specify the full mount commands.
  - 'mount --verbose --types xfs /dev/nvme1n1 /var/cyhy/reports/output'

output:
  - all: '| tee -a /var/log/cloud-init-output.log'
