---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform_egress_pub"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform_nessus_only"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform_route_53"
    schedule:
      interval: "weekly"
