---
- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: sudo
  roles:
    - xfs
    - cyhy_reports
    - cyhy_mailer
  vars:
    texmf_buffer_size: 1000000
  vars_files:
    - vars/maxmind_license_key.yml
