---
- hosts: all
  name: Update the base image and install python
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - pip
    - cyhy_runner
    - nmap

# MongoDB doesn't like transparent huge pages:
# https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/
- hosts: mongo
  name: Install and configure MongoDB and xfsprogs
  become: yes
  become_method: sudo
  roles:
    - xfs
    - mongo
    - {
        role: disable_thp,
        disable_thp_before_service: mongod
      }

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - pip
    - cyhy_runner
    - nessus

- hosts: docker
  name: Install Docker
  become: yes
  become_method: sudo
  roles:
    - docker

# Redis doesn't like transparent huge pages:
# https://redis.io/topics/latency
- hosts: bod_docker
  name: Configure Docker host for BOD 18-01 scanning
  become: yes
  become_method: sudo
  roles:
    - bod_docker
    - {
        role: disable_thp,
        disable_thp_before_service: docker
      }
