---
- hosts: all
  name: Update the base image, install python, add banner, persist journald
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - journald

# The bastion should have as little installed as possible, since it's
# exposed to the cruel world
- hosts: all:!bastion
  name: Install htop
  become: yes
  become_method: sudo
  roles:
    - htop

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - nmap
    - more_ephemeral_ports

# MongoDB doesn't like transparent huge pages:
# https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/
# Disable NUMA since we are deploying Mongo on a NUMA instance in Production
# https://docs.mongodb.com/v3.2/administration/production-notes/#mongodb-and-numa-hardware
- hosts: mongo
  name: Install and configure MongoDB and xfsprogs
  become: yes
  become_method: sudo
  roles:
    - xfs
    - numactl
    - disable_numa
    - mongo
    - {
        role: disable_thp,
        disable_thp_before_service: mongod
      }

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - more_ephemeral_ports

- hosts: docker
  name: Install Docker
  become: yes
  become_method: sudo
  roles:
    - docker

# Redis doesn't like transparent huge pages:
# https://redis.io/topics/latency
- hosts: bod_docker
  name: Configure Docker host for BOD 18-01 scanning and reporting
  become: yes
  become_method: sudo
  roles:
    - xfs
    - orchestrator
    - cyhy_mailer
    - {
        role: disable_thp,
        disable_thp_before_service: docker
      }

- hosts: cyhy_commander
  name: Install and configure cyhy-commander
  become: yes
  become_method: sudo
  roles:
    - cyhy_commander

# In production, the CyHy reporter instance is a c5 instance type.
# These instance types expose EBS volumes as NVMe block devices.
- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: sudo
  roles:
    - nvme
    - xfs
    - cyhy_reporter
    - cyhy_mailer

- hosts: cyhy_feeds
  name: Install and configure cyhy-feeds
  become: yes
  become_method: sudo
  roles:
    - cyhy_feeds

- hosts: cyhy_archive
  name: Install cyhy-archive helper script
  become: yes
  become_method: sudo
  roles:
    - cyhy_archive
