---
# The instance types used for almost all the instances expose EBS
# volumes as NVMe block devices, so that's why we need nvme here.
- hosts: all
  name: Update the base image, install python, add banner, persist journald
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - nvme
    - banner
    - persist_journald

# The bastion should have as little installed as possible, since it's
# exposed to the cruel world
- hosts: all:!bastion
  name: Install htop
  become: yes
  become_method: sudo
  roles:
    - htop

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - nmap
    - more_ephemeral_ports

- hosts: mongo
  name: Install and configure MongoDB and xfsprogs
  become: yes
  become_method: sudo
  roles:
    - xfs
    - mongo
    - cyhy_feeds

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - nessus
    - more_ephemeral_ports

- hosts: docker
  name: Install Docker
  become: yes
  become_method: sudo
  roles:
    - docker

- hosts: bod_docker
  name: Configure Docker host for BOD 18-01 scanning and reporting
  become: yes
  become_method: sudo
  roles:
    - xfs
    - orchestrator
    - cyhy_mailer
    - code_gov_update

- hosts: cyhy_commander
  name: Install and configure cyhy-commander
  become: yes
  become_method: sudo
  roles:
    - cyhy_commander

- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: sudo
  roles:
    - xfs
    - cyhy_reporter
    - cyhy_mailer

- hosts: cyhy_dashboard
  name: Install and configure cyhy-dashboard
  become: yes
  become_method: sudo
  roles:
    - cyhy_dashboard
    - docker

- hosts: cyhy_archive
  name: Install cyhy-archive helper script
  become: yes
  become_method: sudo
  roles:
    - cyhy_archive
