- src: https://github.com/cisagov/ansible-role-banner
  name: banner
- src: https://github.com/cisagov/ansible-role-client-cert-update
  name: client_cert_update
- src: https://github.com/cisagov/ansible-role-code-gov-update
  name: code_gov_update
- src: https://github.com/cisagov/ansible-role-cyhy-mailer
  name: cyhy_mailer
- src: https://github.com/GekoCloud/ansible-role-disable-thp
  name: disable_thp
- src: https://github.com/cisagov/ansible-role-docker
  name: docker
- src: https://github.com/cisagov/ansible-role-htop
  name: htop
- src: https://github.com/cisagov/ansible-role-pip
  name: pip
- src: https://github.com/cisagov/ansible-role-python
  name: python
