language: python

matrix:
  include:
    # We need python 3.7 in order to run the configure.py script, and
    # only the xenial TravisCI images have python 3.7 available.
    - python: 3.7
      dist: xenial
      sudo: true

# Install terraform and ansible
before_install:
  - echo $(which packer)
  - wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - sudo pip install ansible

# Travis' Xenial builds run on GCE and do not have any AWS
# credentials.  Therefore our packer tests must use --syntax-only.
#
# We don't initialize the Terraform backend because Travis doesn't
# have credentials to connect to our AWS S3 bucket where the Terraform
# state is stored.
#
# We don't check Terraform variables because we don't have a tfvars
# file to use.
script:
  - for f in $(ls packer/*.json); do packer validate -syntax-only $f; done
  - cd terraform && ./configure.py && cd ..
  - for d in terraform terraform_egress_pub terraform_nessus_only terraform_route_53; do cd $d; terraform init -backend=false .; terraform validate .; cd ..; done
