---
# tasks file for pip

# Debian, but not mongo because mongo AMI is based on Debian Jessie
- name: Install pip
  apt:
    name: 'python-pip'
    state: latest
  when:
    - "'debian' in group_names"
    - "'mongo' not in group_names"

# Debian and mongo because mongo AMI is based on Debian Jessie
- name: Install pip
  easy_install:
    name: pip
    state: latest
  when:
    - "'debian' in group_names"
    - "'mongo' in group_names"

# python-dev is usually needed with pip to build the wheels
- name: Install python-dev
  apt:
    name:
      - python-dev
    state: latest
  when:
    - "'debian' in group_names"
    - "'mongo' in group_names"

# pip is already installed on Amazon Linux by default, so there is
# nothing to be done in that case
# - name: Install pip (amazon-linux group only)
#   when: "'amazon-linux' in group_names"
#   yum:
#     name: 'python-pip'
#     state: latest
