---
# tasks file for cyhy_runner

- name: Create the /tmp/cyhy-runner directory
  file:
    path: /tmp/cyhy-runner
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download and untar the cyhy-runner tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-runner/tarball/develop?access_token={{ lookup('aws_ssm', '/github/oauth_token') }}"
    dest: /tmp/cyhy-runner
    remote_src: yes
    owner: root
    group: root
    extra_opts:
      - "--strip-components=1"

#
# Now we need to install the cyhy-runner dependencies
#
- name: Install docutils, since cyhy-runner needs it
  pip:
    name:
      - docutils

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip 
# - name: Install python dependencies for cyhy-runner
#   pip:
#     chdir: /var/cyhy/cyhy-runner
#     requirements: requirements.txt
- name: Install python dependencies for cyhy-runner
  command: pip install /tmp/cyhy-runner

# The runner directory is created in this directory
- name: Create the /var/cyhy/runner directory
  file:
    path: /var/cyhy/runner
    state: directory
    owner: root
    group: root
    mode: 0755

# Create the log directory
- name: Create the /var/log/cyhy directory
  file:
    path: /var/log/cyhy
    state: directory
    owner: root
    group: root
    mode: 0755

# Copy the systemd unit file
- name: Copy the systemd unit file for cyhy-runner
  copy:
    src: cyhy-runner.service
    dest: /lib/systemd/system/cyhy-runner.service
    mode: 0644
  when: ansible_os_family == "Debian"

# Copy the SysV init file
- name: Copy the SysV init file for cyhy-runner
  copy:
    src: cyhy-runner
    dest: /etc/init.d/cyhy-runner
    mode: 0755
  when: ansible_os_family == "RedHat"

# Enable cyhy-runner
- name: Enable cyhy-runner
  service:
    name: cyhy-runner
    enabled: yes

#
# Cleanup
#
- name: Delete /tmp/cyhy-runner
  file:
    path: /tmp/cyhy-runner
    state: absent
