---
# tasks file for cyhy_runner

- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml
  become: no

- name: Create the /var/cyhy/cyhy-runner directory
  file:
    path: /var/cyhy/cyhy-runner
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download and untar the cyhy-runner tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-runner/tarball/develop?access_token={{ github_oauth_token }}"
    dest: /var/cyhy/cyhy-runner
    remote_src: yes
    owner: root
    group: root
    extra_opts:
      - "--strip-components=1"

- name: Delete local copy of GitHub OAuth token
  local_action:
    module: file
    path: /tmp/github_oauth_token.yml
    state: absent
  become: no
