---
# tasks file for cyhy_reporter

#
# Set up /etc/cyhy/cyhy.conf
#
- name: Create the /etc/cyhy directory
  file:
    path: /etc/cyhy
    state: directory

- name: Create /etc/cyhy/cyhy.conf
  copy:
    dest: /etc/cyhy/cyhy.conf
    owner: cyhy
    group: cyhy
    mode: 0660
    content: |
      [DEFAULT]
      default-section = cyhy
      database-uri = mongodb://database1.cyhy:27017/
      report-key = {{ lookup('aws_ssm', '/cyhy/master_report_key') }}

      [cyhy]
      database-uri = mongodb://{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/user') }}:{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/password') }}@database1.cyhy:27017/{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/database') }}
      database-name = {{ lookup('aws_ssm', '/cyhy/mongo/users/commander/database') }}

      [scan]
      database-uri = mongodb://{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/user') }}:{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/password') }}@database1.cyhy:27017/{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/database') }}
      database-name = {{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/database') }}

#
# Create cron job for snapshot, CyHy report, and CybEx scorecard generation
#
- name: Add /usr/local/bin to cron's path
  cron:
    env: yes
    name: PATH
    value: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    user: cyhy
  when: production_workspace
# This cron job runs at midnight UTC on Sunday mornings.  The BOD
# scanning is long since completed by that time.
#
# Disable the reporting cron job for now until the BOD scanning and
# the CyHy reporting share a common redis DB.
# - name: Create a cron job for report generation
#   cron:
#     name: "Snapshot, CyHy report, and CybEx scorecard generation"
#     minute: 0
#     hour: 0
#     weekday: 0
#     user: cyhy
#     job: cd /var/cyhy/reports && ./create_snapshots_reports_scorecard.py --no-dock cyhy scan 2>&1 | /usr/bin/logger -t cyhy-reports
#   when: production_workspace

#
# Add users to the cyhy group
#
- name: Load users from YML file
  local_action:
    module: include_vars
    file: ../../../../terraform/scripts/user_ssh_setup.yml
    name: ssh_users
  become: no

- name: Add known users to the cyhy group
  user:
    name: "{{ item }}"
    groups:
      - cyhy
    append: yes
  loop: "{{ ssh_users.users | map(attribute='name') | list }}"
