---
# tasks file for cyhy_reporter

#
# Replace commander.conf password
#
- name: Grab mongo users from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users token from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

#
# Set up /etc/cyhy/cyhy.conf
#
- name: Create the /etc/cyhy directory
  file:
    path: /etc/cyhy
    state: directory

- name: Create /etc/cyhy/cyhy.conf
  copy:
    dest: /etc/cyhy/cyhy.conf
    owner: cyhy
    group: cyhy
    mode: 0660
    content: |
      [DEFAULT]
      default-section = cyhy
      database-uri = mongodb://localhost:27017/
      report-key =

      [cyhy]
      database-uri = mongodb://reporter:{{ mongo_users.other_users | selectattr("user", "eq", "reporter") | map(attribute="password") | first }}@database1:27017/cyhy
      database-name = cyhy

      [scan]
      database-uri = mongodb://scan-reader:{{ mongo_users.other_users | selectattr("user", "eq", "scan-reader") | map(attribute="password") | first }}@database1:27017/scan
      database-name = scan

#
# Cleanup
#
- name: Delete /tmp/mongo_users.yml
  local_action:
    module: file
    path: /tmp/mongo_users.yml
    state: absent
  become: no

#
# Add users to the cyhy group
#
- name: Load users from YML file
  local_action:
    module: include_vars
    file: ../../../../terraform/scripts/user_ssh_setup.yml
    name: ssh_users
  become: no

- name: Add known users to the cyhy group
  user:
    name: "{{ item }}"
    groups:
      - cyhy
    append: yes
  loop: "{{ ssh_users.users | map(attribute='name') | list }}"
