---
# tasks file for cyhy_commander

#
# Install curl and unzip; they are needed by cyhy_core/var/load_places.sh
#
- name: Install curl and unzip
  package:
    name:
      - curl
      - unzip
    state: latest

- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml
  become: no

#
# Grab the cyhy-core code
#
- name: Create the /tmp/cyhy-core directory
  file:
    path: /tmp/cyhy-core
    state: directory

- name: Download and untar the cyhy-core tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-core/tarball/develop?access_token={{ github_oauth_token }}"
    dest: /tmp/cyhy-core
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-core
#   pip:
#     name: file:///tmp/cyhy-core
- name: Install cyhy-core
  command: pip install /tmp/cyhy-core

#
# Grab the cyhy-commander code
#
- name: Create the /tmp/cyhy-commander directory
  file:
    path: /tmp/cyhy-commander
    state: directory

- name: Download and untar the cyhy-commander tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-commander/tarball/develop?access_token={{ github_oauth_token }}"
    dest: /tmp/cyhy-commander
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Now we need to install the cyhy-commander dependencies
#
# TODO: Figure out why we can't just put docutils in cyhy-commander/setup.py
- name: Install docutils, since cyhy-commander needs it
  pip:
    name:
      - docutils

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-commander
#   pip:
#     name: file:///tmp/cyhy-commander
- name: Install cyhy-commander
  command: pip install /tmp/cyhy-commander

# The commander directory is created in this directory
- name: Create the /var/cyhy/commander directory
  file:
    path: /var/cyhy/commander
    state: directory

# Create the log directory
- name: Create the /var/log/cyhy directory
  file:
    path: /var/log/cyhy
    state: directory

# Copy the systemd unit file
- name: Copy the systemd unit file for cyhy-commander
  copy:
    src: cyhy-commander.service
    dest: /lib/systemd/system/cyhy-commander.service
    mode: 0644

# Don't enable cyhy-commander here; we do that when we spin up an instance
# so remaining setup tasks can be completed first

#
# Cleanup
#
- name: Delete /tmp/cyhy-core
  file:
    path: /tmp/cyhy-core
    state: absent

- name: Delete /tmp/cyhy-commander
  file:
    path: /tmp/cyhy-commander
    state: absent

- name: Delete local copy of GitHub OAuth token
  local_action:
    module: file
    path: /tmp/github_oauth_token.yml
    state: absent
  become: no
