---
# tasks file for cyhy_commander

#
# Copy ssh private key to local tmp dir
#
- name: Grab ssh private key from S3 for cyhy user
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: cyhy_private_id_ed25519
    dest: /tmp/id_ed25519
    mode: get
  become: no

#
# Copy private key to new instance
#
- name: Copy ssh private key for cyhy user
  copy:
    src: /tmp/id_ed25519
    dest: /var/cyhy/.ssh/id_ed25519
    owner: cyhy
    group: cyhy
    mode: 0600  

#
# Delete local tmp private key
#
- name: Delete local copy of ssh private key for cyhy user
  local_action:
    module: file
    path: /tmp/id_ed25519
    state: absent
  become: no
