---
# tasks file for cyhy_commander

#
# Copy ssh private key to local temp dir
#
- name: Grab ssh private key from S3 for cyhy user
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: cyhy_private_id_ed25519
    dest: /tmp/id_ed25519
    mode: get
  become: no

#
# Copy private key to new instance
#
- name: Copy ssh private key for cyhy user
  copy:
    src: /tmp/id_ed25519
    dest: /var/cyhy/.ssh/id_ed25519
    owner: cyhy
    group: cyhy
    mode: 0600

#
# Delete local copy of private key
#
- name: Delete local copy of ssh private key for cyhy user
  local_action:
    module: file
    path: /tmp/id_ed25519
    state: absent
  become: no

#
# Create the cyhy directory in etc for commander conf
#
- name: Create the /etc/cyhy directory
  file:
    path: /etc/cyhy
    state: directory

#
# Copy the cyhy-commander conf file
#
- name: Copy the configuration file for cyhy-commander
  copy:
    src: commander.conf
    dest: /etc/cyhy/commander.conf
    mode: 0644

#
# Replace commander.conf password
#

- name: Grab mongo users from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users token from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

- name: Configure commander.conf to use commander as mongo user
  lineinfile:
    dest: /etc/cyhy/commander.conf
    regexp: 'database-uri ='
    state: present
    line: 'database-uri = mongodb://commander:{{ mongo_users.other_users | selectattr("user", "eq", "commander") | map(attribute="password") | first }}@{{ mongo_host }}:27017/cyhy'

- name: Enable and start cyhy-commander
  service:
    name: cyhy-commander
    enabled: yes
    state: started

- name: Delete /tmp/mongo_users.yml
  file:
    path: /tmp/mongo_users.yml
    state: absent
