---
# tasks file for cyhy_commander

#
# Copy ssh private key to local temp dir
#
- name: Grab ssh private key from S3 for cyhy user
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: cyhy_private_id_ed25519
    dest: /tmp/id_ed25519
    mode: get
  become: no

#
# Copy private key to new instance
#
- name: Copy ssh private key for cyhy user
  copy:
    src: /tmp/id_ed25519
    dest: /var/cyhy/.ssh/id_ed25519
    owner: cyhy
    group: cyhy
    mode: 0600

#
# Delete local copy of private key
#
- name: Delete local copy of ssh private key for cyhy user
  local_action:
    module: file
    path: /tmp/id_ed25519
    state: absent
  become: no

#
# Create the cyhy directory in etc for commander conf
#
- name: Create the /etc/cyhy directory
  file:
    path: /etc/cyhy
    state: directory

#
# Copy the cyhy-commander conf file
#
- name: Copy the configuration file for cyhy-commander
  copy:
    src: commander.conf
    dest: /etc/cyhy/commander.conf
    mode: 0644

#
# Replace commander.conf password
#
- name: Grab mongo users from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users token from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

- name: Configure commander.conf to use commander as mongo user
  lineinfile:
    dest: /etc/cyhy/commander.conf
    regexp: 'database-uri ='
    state: present
    line: 'database-uri = mongodb://commander:{{ mongo_users.other_users | selectattr("user", "eq", "commander") | map(attribute="password") | first }}@{{ mongo_host }}:27017/cyhy'

- name: Enable and start cyhy-commander
  service:
    name: cyhy-commander
    enabled: yes
    state: started

- name: Delete /tmp/mongo_users.yml
  file:
    path: /tmp/mongo_users.yml
    state: absent

#
# Grab the files we need to create the "places" collection from cyhy-core
#
- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml
  become: no

- name: Create the /tmp/cyhy-places/scripts directory
  file:
    path: /tmp/cyhy-places/scripts
    state: directory

- name: Create the /tmp/cyhy-places/extras directory
  file:
    path: /tmp/cyhy-places/extras
    state: directory

- name: Download load_places.sh from GitHub
  shell: "curl -o /tmp/cyhy-places/scripts/load_places.sh https://{{ github_oauth_token }}@raw.githubusercontent.com/jsf9k/cyhy-core/develop/var/load_places.sh"

- name: Download GNIS_data_import.py from GitHub
  shell: "curl -o /tmp/cyhy-places/scripts/GNIS_data_import.py https://{{ github_oauth_token }}@raw.githubusercontent.com/jsf9k/cyhy-core/develop/var/GNIS_data_import.py"

- name: Make load_places.sh script executable
  file:
    path: /tmp/cyhy-places/scripts/load_places.sh
    mode: 0755

- name: Make GNIS_data_import.py script executable
  file:
    path: /tmp/cyhy-places/scripts/GNIS_data_import.py
    mode: 0755

- name: Download ADDL_CYHY_PLACES.txt from GitHub
  shell: "curl -o /tmp/cyhy-places/extras/ADDL_CYHY_PLACES.txt https://{{ github_oauth_token }}@raw.githubusercontent.com/jsf9k/cyhy-core/develop/extras/ADDL_CYHY_PLACES.txt"

#
# Run script to create the "places" collection
#
- name: Load data to places collection
  shell: /tmp/cyhy-places/scripts/load_places.sh

#
# Cleanup
#
# - name: Delete /tmp/cyhy-places
#   file:
#     path: /tmp/cyhy-places
#     state: absent
#
# - name: Delete local copy of GitHub OAuth token
#   local_action:
#     module: file
#     path: /tmp/github_oauth_token.yml
#     state: absent
#   become: no
