---
# tasks file for cyhy_commander

#
# Copy private key to new instance
#
- name: Copy ssh private key for cyhy user
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: /var/cyhy/.ssh/id_ed25519
    owner: cyhy
    group: cyhy
    mode: 0600

#
# Create the cyhy directory in etc for commander conf
#
- name: Create the /etc/cyhy directory
  ansible.builtin.file:
    path: /etc/cyhy
    state: directory

#
# Copy the cyhy-commander conf file
#
- name: Copy the configuration file for cyhy-commander
  ansible.builtin.copy:
    src: commander.conf
    dest: /etc/cyhy/commander.conf
    mode: 0644
#
# Create empty cyhy ssh config with cyhy as owner and group
#
- name: Create empty ssh config file
  ansible.builtin.file:
    path: /var/cyhy/.ssh/config
    state: touch
    owner: cyhy
    group: cyhy

#
# Replace commander.conf password
#
- name: Configure commander.conf to use commander as mongo user
  ansible.builtin.lineinfile:
    dest: /etc/cyhy/commander.conf
    regexp: "database-uri ="
    state: present
    line: "database-uri = mongodb://{{ commander_user }}:{{ commander_pw }}@database1.cyhy:27017/{{ commander_db }}"

- name: Enable and start cyhy-commander
  ansible.builtin.service:
    name: cyhy-commander
    enabled: yes
    state: restarted

#
# Grab the files we need to create the "places" collection from cyhy-core
#
- name: Create the /tmp/cyhy-places/scripts directory
  ansible.builtin.file:
    path: /tmp/cyhy-places/scripts
    state: directory

- name: Create the /tmp/cyhy-places/extras directory
  ansible.builtin.file:
    path: /tmp/cyhy-places/extras
    state: directory

- name: Download load_places.sh from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/cisagov/cyhy-core/develop/var/load_places.sh"
    dest: /tmp/cyhy-places/scripts/load_places.sh
    mode: 0755

- name: Download GNIS_data_import.py from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/cisagov/cyhy-core/develop/var/GNIS_data_import.py"
    dest: /tmp/cyhy-places/scripts/GNIS_data_import.py
    mode: 0755

- name: Download ADDL_CYHY_PLACES.txt from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/cisagov/cyhy-core/develop/extras/ADDL_CYHY_PLACES.txt"
    dest: /tmp/cyhy-places/extras/ADDL_CYHY_PLACES.txt
    mode: 0644

- name: Check if cyhy.conf already exists
  ansible.builtin.stat:
    path: /etc/cyhy/cyhy.conf
  register: cyhy_conf_result

#
# Set up /etc/cyhy/cyhy.conf with commander creds
#
# This is a little messy.  The real solution is to just create a
# cyhy.conf with credentials for each user in mongo_users.other_users.
# That will cause some heartburn, though, since the credential
# sections will have to be named using the MongoDB username.  That
# will necessitate some changes elsewhere in the code where named
# sections from cyhy.conf are explicitly referenced.
- name: Create cyhy.conf (with commander credentials) if it doesn't exist
  ansible.builtin.copy:
    dest: /etc/cyhy/cyhy.conf
    owner: cyhy
    group: cyhy
    mode: 0660
    content: |
      [DEFAULT]
      default-section = production
      database-uri = mongodb://database1.cyhy:27017/
      report-key =

      ; BEGIN ANSIBLE MANAGED BLOCK commander
      [production]
      database-uri = mongodb://{{ commander_user }}:{{ commander_pw }}@database1.cyhy:27017/{{ commander_db }}
      database-name = {{ commander_db }}
      ; END ANSIBLE MANAGED BLOCK commander
  when: cyhy_conf_result.stat.exists == False

- name: Add commander credentials block to cyhy.conf if necessary
  ansible.builtin.blockinfile:
    path: /etc/cyhy/cyhy.conf
    marker: '; {mark} ANSIBLE MANAGED BLOCK commander'
    block: |
      [production]
      database-uri = mongodb://{{ commander_user }}:{{ commander_pw }}@database1.cyhy:27017/{{ commander_db }}
      database-name = {{ commander_db }}
  when: cyhy_conf_result.stat.exists == True

#
# Run script to create the "places" collection
#
# Note that we have to turn on pipelining, as described here:
# https://docs.ansible.com/ansible/latest/user_guide/become.html#becoming-an-unprivileged-user
#
- name: Load data to places collection as the cyhy user
  ansible.builtin.shell: /tmp/cyhy-places/scripts/load_places.sh
  become_user: cyhy
  vars:
    ansible_ssh_pipelining: yes

#
# Cleanup
#
- name: Delete /tmp/cyhy-places
  ansible.builtin.file:
    path: /tmp/cyhy-places
    state: absent

#
# Run cyhy-nvdsync daily at 0815 (UTC) as cyhy user
#
- name: Set up nightly cron job to sync NVD data
  ansible.builtin.cron:
    name: Nightly cyhy-nvdsync
    hour: '8'
    minute: '15'
    user: cyhy
    job: /usr/local/bin/cyhy-nvdsync --use-network 2>&1 | /usr/bin/logger -t cyhy-nvdsync

#
# Run cyhy-kevsync daily at 0845 (UTC) as cyhy user
#
- name: Set up nightly cron job to sync KEV data
  ansible.builtin.cron:
    name: Nightly cyhy-kevsync
    hour: '8'
    minute: '45'
    user: cyhy
    job: /usr/local/bin/cyhy-kevsync 2>&1 | /usr/bin/logger -t cyhy-kevsync
