---
# tasks file for cyhy_reporter

#
# Grab the ncats-webd code
#
- name: Create the /tmp/ncats-webd directory
  file:
    path: /tmp/ncats-webd
    state: directory

- name: Download and untar the ncats-webd tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/ncats-webd/tarball/develop?access_token={{ oauth_token }}"
    dest: /tmp/ncats-webd
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install ncats-webd
#

# These dependencies are from here:
# https://github.com/jsf9k/cal-overlay/blob/develop/net-analyzer/ncats-webd/ncats-webd-2.0.2.ebuild#L31-L47
#
# I'd prefer to install the python dependencies via pip, but then I
# get errors about modules being built with a different version of
# numpy than what is on the host.  Doing it this way seems to work
# much better.
- name: Install cyhy-webd dependencies
  package:
    name:
      - python-numpy
      - python-dateutil
      - python-netaddr
      - python-pandas
      - python-docopt
      - python-flask
      - python-flask-sockets
      - python-apscheduler
      - python-eventlet
      - python-schedule
      - python-gunicorn
    state: latest

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install ncats-webd
#   pip:
#     name: file:///var/cyhy/ncats-webd
- name: Install ncats-webd
  command: pip install /tmp/ncats-webd

#
# Grab the cyhy-reports code
#
- name: Create the /tmp/cyhy-reports directory
  file:
    path: /tmp/cyhy-reports
    state: directory

- name: Download and untar the cyhy-reports tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-reports/tarball/develop?access_token={{ oauth_token }}"
    dest: /tmp/cyhy-reports
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install cyhy-reports
#

# These dependencies are from here:
# https://github.com/jsf9k/cal-overlay/blob/develop/net-analyzer/cyhy-reports/cyhy-reports-1.0.12.ebuild#L31-L49
#
# I'd prefer to install the python dependencies via pip, but then I
# get errors about modules being built with a different version of
# numpy than what is on the host.  Doing it this way seems to work
# much better.
- name: Install cyhy-reports dependencies
  package:
    name:
      - python-mpltoolkits.basemap
      - python-numpy
      - python-dateutil
      - python-netaddr
      - python-pystache
      - python-pandas
      - python-progressbar
      - python-docopt
      - python-unicodecsv
      - python-pypdf2
      - texlive
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-science
      - texlive-xetex
    state: latest

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-reports
#   pip:
#     name: file:///tmp/cyhy-reports
- name: Install cyhy-reports
  command: pip install /tmp/cyhy-reports

- name: Create the /var/cyhy/reports directory
  file:
    path: /var/cyhy/reports
    state: directory

- name: Copy the reporting script
  copy:
    src: /tmp/cyhy-reports/extras/create_snapshots_reports_scorecard.py
    dest: /var/cyhy/reports/create_snapshots_reports_scorecard.py
    mode: 0755
    remote_src: yes

# rsync is required by synchronize
- name: Install rsync
  package:
    name: rsync
    state: latest

- name: Copy the cyhy-reports fonts
  synchronize:
    src: /tmp/cyhy-reports/cyhy_report/assets/Fonts/
    dest: /usr/local/share/fonts
  delegate_to: "{{ inventory_hostname }}"

- name: Install the cyhy-reports fonts
  command: fc-cache --system-only

- name: Create the mount point for the reports volume
  file:
    path: /var/cyhy/reports/output
    state: directory

#
# Cleanup
#
- name: Delete /tmp/cyhy-reports
  file:
    path: /tmp/cyhy-reports
    state: absent
