---
# tasks file for cyhy_reporter

- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml
  become: no

#
# Grab the cyhy-core code
#
- name: Create the /tmp/cyhy-core directory
  file:
    path: /tmp/cyhy-core
    state: directory

- name: Download and untar the cyhy-core tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-core/tarball/develop?access_token={{ github_oauth_token }}"
    dest: /tmp/cyhy-core
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install cyhy-core
#

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-core
#   pip:
#     name: file:///var/cyhy/cyhy-core
- name: Install cyhy-core
  command: pip install /tmp/cyhy-core

#
# Grab the cyhy-reports code
#
- name: Create the /tmp/cyhy-reports directory
  file:
    path: /tmp/cyhy-reports
    state: directory

- name: Download and untar the cyhy-reports tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-reports/tarball/develop?access_token={{ github_oauth_token }}"
    dest: /tmp/cyhy-reports
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install cyhy-reports
#
- name: Install libgeos-dev, since basemap needs it and cyhy-reports needs basemap
  apt:
    name:
      - libgeos-dev
    state: latest

- name: Install basemap, since cyhy-reports needs it
  pip:
    name:
      - https://github.com/matplotlib/basemap/archive/master.zip

- name: Install some LaTeX packages that cyhy-reports needs
  apt:
    name:
      - texlive
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-xetex
    state: latest

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-reports
#   pip:
#     name: file:///tmp/cyhy-reports
- name: Install cyhy-reports
  command: pip install /tmp/cyhy-reports

- name: Create the /var/cyhy/reports directory
  file:
    path: /var/cyhy/reports
    state: directory

- name: Copy the reporting script
  copy:
    src: /tmp/cyhy-reports/extras/create_snapshots_reports_scorecard.py
    dest: /var/cyhy/reports/create_snapshots_reports_scorecard.py
    mode: 755
    remote_src: yes

#
# Cleanup
#
- name: Delete /tmp/cyhy-core
  file:
    path: /tmp/cyhy-core
    state: absent

- name: Delete /tmp/cyhy-reports
  file:
    path: /tmp/cyhy-reports
    state: absent

- name: Delete local copy of GitHub OAuth token
  local_action:
    module: file
    path: /tmp/github_oauth_token.yml
    state: absent
  become: no
