---
# tasks file for cyhy_archive

- name: Create the /var/cyhy/scripts directory
  file:
    path: /var/cyhy/scripts
    state: directory

- name: Download cyhy_archive.sh from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/jsf9k/cyhy-core/develop/var/cyhy_archive.sh"
    headers:
      Authorization: "token {{ github_oauth_token }}"
    dest: /var/cyhy/scripts/cyhy_archive.sh
    mode: 0755
