---
# tasks file for cyhy_mailer

#
# Load mongo users and passwords into a variable
#
- name: Grab mongo users and passwords from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users and passwords from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

- name: Delete local copy of mongo users
  local_action:
    module: file
    path: /tmp/mongo_users.yml
    state: absent
  become: no


#
# cyhy-mailer secrets
#
# The cyhy-mailer container does not run as root, so the creds files
# need to be globally readable.  docker-compose does allow one to
# specify the uid, gid, and mode of the secrets files, but that only
# works in swarm mode.
#
- name: Create the secrets directory for cyhy-mailer
  file:
    path: /var/cyhy/cyhy-mailer/secrets
    owner: cyhy
    group: cyhy
    state: directory

- name: Create the cyhy-mailer credentials file to allow reading the cyhy database
  copy:
    dest: /var/cyhy/cyhy-mailer/secrets/database_creds.yml
    owner: cyhy
    group: cyhy
    mode: 0444
    content: |
      version: '1'

      database:
        name: cyhy
        uri: mongodb://reporter:{{ mongo_users.other_users | selectattr("user", "eq", "reporter") | map(attribute="password") | first }}@{{ mongo_host }}:27017/cyhy

- name: Create a temporary directory to store the cyhy-mailer AWS SMTP credentials
  local_action:
    module: file
    path: /tmp/secrets/smtp
    state: directory
  become: no

- name: Grab the cyhy-mailer AWS SMTP credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: cyhy-mailer_secrets/smtp_creds.yml
    dest: /tmp/secrets/smtp/smtp_creds.yml
    mode: get
  become: no

- name: Copy the cyhy-mailer AWS SMTP credentials
  copy:
    src: /tmp/secrets/smtp/smtp_creds.yml
    dest: /var/cyhy/cyhy-mailer/secrets/smtp_creds.yml
    owner: cyhy
    group: cyhy
    mode: 0444

- name: Delete local copy of cyhy-mailer secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: absent
  become: no


#
# Create a cron job for the sending of reports
#
# - name: Add /usr/local/bin to cron's path
#   cron:
#     env: yes
#     name: PATH
#     value: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
#     user: cyhy
#   when: production_workspace
# This cron job runs at noon UTC on Mondays.  The BOD reports are long
# since completed by that time.
# - name: Create a cron job for sending BOD 18-01 reports
#   cron:
#     name: "Sending BOD 18-01 reports"
#     minute: 0
#     hour: 12
#     weekday: 1
#     user: cyhy
#     job: cd /var/cyhy/cyhy-mailer && docker-compose up -d 2>&1 | /usr/bin/logger -t cyhy-mailer
#   when: production_workspace


#
# Add users to the cyhy group
#
- name: Load users from YML file
  local_action:
    module: include_vars
    file: ../../../../terraform/scripts/user_ssh_setup.yml
    name: ssh_users
  become: no

- name: Add known users to the cyhy group
  user:
    name: "{{ item }}"
    groups:
      - cyhy
    append: yes
  loop: "{{ ssh_users.users | map(attribute='name') | list }}"
