---
# tasks file for cyhy_core

#
# Grab the cyhy-core code
#
- name: Create the /tmp/cyhy-core directory
  file:
    path: /tmp/cyhy-core
    state: directory

- name: Download and untar the cyhy-core tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/cyhy-core/tarball/develop?access_token={{ oauth_token }}"
    dest: /tmp/cyhy-core
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install cyhy-core
#

# Thanks to https://github.com/ansible/ansible/issues/37912 I have to
# do some chicanery here instead of just using pip
# - name: Install cyhy-core
#   pip:
#     name: file:///var/cyhy/cyhy-core
- name: Install cyhy-core
  command: pip install /tmp/cyhy-core

#
# Cleanup
#
- name: Delete /tmp/cyhy-core
  file:
    path: /tmp/cyhy-core
    state: absent
