---
# tasks file for mongo
- name: Grab mongo users and paswords from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users and passwords from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

- name: Check if any mongo users already exist
  shell: mongo --eval 'db.getUsers()' admin
  ignore_errors: true
  register: checkifmongousers
  changed_when: false

# HACK ALERT - Part 1: Install latest pymongo in order to use ansible mongodb_user
- name: Install latest pymongo
  pip:
    name: pymongo
    state: latest

- name: Create admin user in admin db (first user, no authentication)
  mongodb_user:
    database: admin
    name: "{{ mongo_users.admin_user.user }}"
    password: "{{ mongo_users.admin_user.password }}"
    roles: userAdminAnyDatabase
    state: present
  when: checkifmongousers.rc == 0

- name: Update admin user in admin db (authenticate as admin)
  mongodb_user:
    login_database: admin
    login_user: "{{ mongo_users.admin_user.user }}"
    login_password: "{{ mongo_users.admin_user.old_password }}"
    database: "{{ mongo_users.admin_user.database }}"
    name: "{{ mongo_users.admin_user.user }}"
    password: "{{ mongo_users.admin_user.password }}"
    roles: "{{ mongo_users.admin_user.roles }}"
    state: present
  when: checkifmongousers.rc != 0

- name: Update other users (authenticate as admin)
  mongodb_user:
    login_database: admin
    login_user: "{{ mongo_users.admin_user.user }}"
    login_password: "{{ mongo_users.admin_user.password }}"
    database: "{{ item.database }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    state: present
  loop: "{{ mongo_users.other_users }}"
  loop_control:
    label: "{{ item.user }}"

# HACK ALERT - Part 2: Revert to older pymongo, needed for cyhy-core
- name: Downgrade to pymongo 2.9.5
  pip:
    name: pymongo
    version: 2.9.5

- name: Delete local copy of mongo user file
  local_action:
    module: file
    path: /tmp/mongo_users.yml
    state: absent
  become: no

- name: Copy mongo configuration file
  template:
    src: mongod.conf
    dest: /etc/mongod.conf
    mode: 644

- name: Restart mongod service to use new configuration
  service:
    name: mongod
    state: restarted
