---
# tasks file for mongo
- name: Check if any mongo users already exist
  shell: mongo --eval 'db.getUsers()' admin
  ignore_errors: true
  register: checkifmongousers
  changed_when: false

# HACK ALERT - Part 1: Install pymongo 3.5 in order to use the Ansible
# mongodb_user module
#
# Note that pymongo > 3.5 will fail right now, so we have to enforce
# an old version:
# * https://jira.mongodb.org/browse/SERVER-34820
# * https://github.com/ansible/ansible/issues/38998
#
# The forced installation of 3.5 should be removed once this issue
# gets resolved.
- name: Install pymongo 3.5.  This should be changed to install the latest once that is possible.
  pip:
    name: pymongo
    version: '3.5'

- name: Create admin user in admin db (first user, no authentication)
  mongodb_user:
    database: "{{ admin_db }}"
    name: "{{ admin_user }}"
    password: "{{ admin_pw }}"
    roles: "{{ admin_roles }}"
    state: present
  when: checkifmongousers.rc == 0

- name: Update admin user in admin db (authenticate as admin)
  mongodb_user:
    login_database: "{{ admin_db }}"
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_old_pw }}"
    database: "{{ admin_db }}"
    name: "{{ admin_user }}"
    password: "{{ admin_pw }}"
    roles: "{{ admin_roles }}"
    state: present
  when: checkifmongousers.rc != 0

- name: Update other users (authenticate as admin)
  mongodb_user:
    login_database: "{{ admin_db }}"
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_pw }}"
    database: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/database') }}"
    name: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/user') }}"
    password: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/password') }}"
    roles: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/roles').split(',') }}"
    state: present
  # Loop over all the users *except* for admin
  loop: "{{ non_admin_users }}"

# HACK ALERT - Part 2: Revert to older pymongo, needed for cyhy-core
- name: Downgrade to pymongo 2.9.5
  pip:
    name: pymongo
    version: 2.9.5

- name: Copy mongo configuration file
  template:
    src: mongod.conf
    dest: /etc/mongod.conf
    mode: 0644

- name: Restart mongod service to use new configuration
  service:
    name: mongod
    state: restarted
