---
# tasks file for mongo
- name: Grab mongo users and paswords from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo uses and passwords from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

- name: Check if any mongo users already exist
  shell: mongo --eval 'db.getUsers()' admin
  ignore_errors: true
  register: checkifmongousers
  changed_when: false

- name: Create admin user in admin db (first user, no authentication)
  mongodb_user:
    database: admin
    name: "{{ mongo_users.admin_user.user }}"
    password: "{{ mongo_users.admin_user.password }}"
    roles: userAdminAnyDatabase
    state: present
  when: checkifmongousers.rc == 0

- name: Update other users in admin db (authenticate as admin)
  mongodb_user:
    login_database: admin
    login_user: "{{ mongo_users.admin_user.user }}"
    login_password: "{{ mongo_users.admin_user.old_password }}"
    database: "{{ mongo_users.admin_user.database }}"
    name: "{{ mongo_users.admin_user.user }}"
    password: "{{ mongo_users.admin_user.password }}"
    roles: "{{ mongo_users.admin_user.roles }}"
    state: present
  when: checkifmongousers.rc == 1

- name: Update other users in admin db (authenticate as admin)
  mongodb_user:
    login_database: admin
    login_user: "{{ mongo_users.admin_user.user }}"
    login_password: "{{ mongo_users.admin_user.password }}"
    database: "{{ item.database }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    state: present
  loop: "{{ mongo_users.other_users }}"

- name: Delete mongo user file
  local_action:
    module: file
    path: /tmp/mongo_users.yml
    state: absent
  become: no
