---
# tasks file for mongo
- name: Check if any mongo users already exist
  shell: mongo --eval 'db.getUsers()' admin
  ignore_errors: true
  register: checkifmongousers
  changed_when: false

# HACK ALERT - Part 1:
# Install pymongo 3.6 in order to use the Ansible mongodb_user module.
- name: Install pymongo 3.6
  pip:
    name: pymongo
    version: '3.6'

- name: Create admin user in admin db (first user, no authentication)
  mongodb_user:
    database: "{{ admin_db }}"
    name: "{{ admin_user }}"
    password: "{{ admin_pw }}"
    roles: "{{ admin_roles }}"
    state: present
  when: checkifmongousers.rc == 0

- name: Update admin user in admin db (authenticate as admin)
  mongodb_user:
    login_database: "{{ admin_db }}"
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_old_pw }}"
    database: "{{ admin_db }}"
    name: "{{ admin_user }}"
    password: "{{ admin_pw }}"
    roles: "{{ admin_roles }}"
    state: present
  when: checkifmongousers.rc != 0

- name: Update other users (authenticate as admin)
  mongodb_user:
    login_database: "{{ admin_db }}"
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_pw }}"
    database: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/database') }}"
    name: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/user') }}"
    password: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/password') }}"
    roles: "{{ lookup('aws_ssm', '/cyhy/mongo/users/{{ item }}/roles').split(',') }}"
    state: present
  # Loop over all the users *except* for admin
  loop: "{{ non_admin_users }}"

# HACK ALERT - Part 2:
# Revert to older pymongo, needed for cyhy-core
- name: Downgrade to pymongo 2.9.5
  pip:
    name: pymongo
    version: 2.9.5

- name: Copy mongo configuration file
  template:
    src: mongod.conf
    dest: /etc/mongod.conf
    mode: 0644

- name: Restart mongod service to use new configuration
  service:
    name: mongod
    state: restarted
