---
# tasks file for nessus

- name: Stop the Nessus service
  service:
    name: nessusd
    state: stopped

#
# Check if a license key is registered and if not register one
#
- name: Check if a license key is registered
  command: /opt/nessus/sbin/nessuscli fetch --check
  register: registered
  failed_when: registered.rc not in [0, 1]

- name: Register a license key if necessary
  command: "/opt/nessus/sbin/nessuscli fetch --register-only {{ nessus_activation_code }}"
  when: registered.rc != 0

#
# Create the Nessus scanner user
#
- name: Grab the existing Nessus users
  command: /opt/nessus/sbin/nessuscli lsuser
  register: users

# The expect Ansible module requires pexpect
- name: Install pexpect
  pip:
    name:
      - pexpect
  when: username not in users.stdout

- name: Create scanner user if necessary
  expect:
    command: "/opt/nessus/sbin/nessuscli adduser {{ username }}"
    responses:
      password: "{{ password }}"
      administrator: y
      BLANK: ""
  when: username not in users.stdout

- name: Update plugins
  command: /opt/nessus/sbin/nessuscli update --plugins-only
  async: 300
  poll: 5
  when: registered.rc != 0

- name: Rebuild the plugin database
  command: /opt/nessus/sbin/nessusd -R
  async: 1200
  poll: 30
  when: registered.rc != 0

- name: Start Nessus service
  service:
    name: nessusd
    state: started

# Copy the nessus_base.py to tmp
- name: Copy the nessus_base python file for importing the base nessus policy
  copy:
    src: nessus_base.py
    dest: /tmp/nessus_base.py
    mode: 0744

- name: Configure nessus base policy to use nessus username
  lineinfile:
    dest: /tmp/nessus_base.py
    regexp: "USER = ''"
    state: present
    line: "USER = '{{ username }}'"

- name: Configure nessus base policy to use nessus password
  lineinfile:
    dest: /tmp/nessus_base.py
    regexp: "PASSWORD = ''"
    state: present
    line: "PASSWORD = '{{ password }}'"

- name: Copy base nessus scan policy to instance tmp
  template:
    src: cyhy-base-nessus8-policy.xml.j2
    dest: /tmp/cyhy-base-nessus8-policy.xml

- name: Run nessus base policy import script
  command: python /tmp/nessus_base.py

#
# Clean up
#
- name: Delete /tmp/cyhy-base-nessus8-policy.xml
  file:
    path: /tmp/cyhy-base-nessus8-policy.xml
    state: absent

- name: Delete /tmp/nessus_base.py
  file:
    path: /tmp/nessus_base.py
    state: absent
