---
# tasks file for cyhy_feeds

- name: Create the /var/cyhy/scripts/cyhy-feeds/cyhy_extracts directory
  file:
    path: /var/cyhy/scripts/cyhy-feeds/cyhy_extracts
    state: directory

- name: Download cyhy extract scripts from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/cisagov/cyhy-feeds/develop/aws_jobs/{{ item }}"
    headers:
    dest: "/var/cyhy/scripts/cyhy-feeds/{{ item }}"
    mode: 0755
  loop:
    - cyhy-data-extract.py
    - dmarc.py

- name: Install dependencies
  package:
    name:
      - gnupg2
      - unzip

# We want to install boto3 and requests via pip but older versions may
# have already been installed via the package manager.  Let's force
# pip to upgrade in case those versions aren't the latest.
- name: Install pip dependencies
  pip:
    name:
      - boto3
      - python-gnupg
      - requests
      - requests_aws4auth
    extra_args: --upgrade
