---
# tasks file for cyhy_feeds
- name: Install unzip
  package:
    name: unzip
    state: latest

- name: Install boto3
  pip:
    name:
      - boto3

- name: Install the package "gnupg2"
  apt:
    name: gnupg2

- name: Install python-gnupg
  pip:
    name:
      - python-gnupg

- name: Install python requests-aws4auth
  pip:
    name:
      - requests_aws4auth

- name: Install python requests
  pip:
    name:
      - requests
