---
# tasks file for cyhy_feeds

- name: Install dependencies
  package:
    name:
      - gnupg2
      - unzip

- name: Install pip dependencies
  pip:
    name:
      - boto3
      - python-gnupg
      - requests
      - requests_aws4auth
