---
- hosts: all
  name: Update the base image
  become: yes
  become_method: sudo
  roles:
    - upgrade

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - nmap

- hosts: mongo
  name: Install and configure MongoDB
  become: yes
  become_method: sudo
  roles:
    - mongo

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - nessus

- hosts: docker
  name: Install Docker
  become: yes
  become_method: sudo
  roles:
    - docker
