---
- hosts: all
  name: Update the base image
  become: yes
  become_method: sudo
  roles:
    - upgrade

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - nmap

- hosts: mongo
  name: Install and configure MongoDB
  become: yes
  become_method: sudo
  roles:
    - mongo
