---
- hosts: all
  name: Update the base image
  become: yes
  become_method: sudo
  roles:
    - upgrade

- hosts: all
  name: Configure ssh
  become: yes
  become_method: sudo
  roles:
    - ssh

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - nmap

- hosts: mongo
  name: Install and configure MongoDB
  become: yes
  become_method: sudo
  roles:
    - mongo

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - nessus
