---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  tasks:
    - name: Add public ip addresses to an dynamic inventory
      add_host:
        name: "{{ host }}"
        groups: "{{ host_groups.split(',') }}"

    - wait_for:
        port: 22
        host: "{{ host }}"
        search_regex: OpenSSH
      delegate_to: "{{ bastion_host }}"
      when: bastion_host is defined

    - wait_for:
        port: 22
        host: "{{ host }}"
        search_regex: OpenSSH
      when: bastion_host is not defined

- hosts: mongo
  name: Configure MongoDB
  become: yes
  become_method: sudo
  roles:
    - mongo

- hosts: docker
  name: Configure Docker hosts
  become: yes
  become_method: sudo
  roles:
    - docker

- hosts: bod_docker
  name: Configure Docker hosts for BOD 18-01 scanning
  become: yes
  become_method: sudo
  roles:
    - bod_docker

- hosts: cyhy_commander
  name: Configure cyhy-commander hosts
  become: yes
  become_method: sudo
  roles:
    - chown_cyhy_dirs
    - cyhy_commander
    - { role: swap, swapfile_size: 2GiB}

- hosts: nmap
  name: Configure nmap scanning hosts
  become: yes
  become_method: sudo
  roles:
    - { role: swap, swapfile_size: 2GiB}

- hosts: cyhy_runner
  name: Configure cyhy-runner hosts
  become: yes
  become_method: sudo
  roles:
    - chown_cyhy_dirs

- hosts: nessus
  name: Configure Nessus hosts
  become: yes
  become_method: sudo
  roles:
    - nessus

- hosts: cyhy_reporter
  name: Configure cyhy-reports hosts
  become: yes
  become_method: sudo
  roles:
    - chown_cyhy_dirs
    - cyhy_reporter

- hosts: cyhy_bastion
  name: Configure cyhy bastion hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_ops

- hosts: cyhy_feeds
  name: Configure cyhy bastion hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_feeds
