collections:
  - community.general
  - name: community.mongodb
    # The last version that officially supports MongoDB 3.6
    version: 1.3.4

roles:
  - src: https://github.com/cisagov/ansible-role-cyhy-logrotate
    name: cyhy_logrotate
  - src: https://github.com/cisagov/ansible-role-mongo-logrotate
    name: mongo_logrotate
