---
# tasks file for cyhy_feeds
- name: Grab GitHub OAuth token from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: github_oauth_token.yml
    dest: /tmp/github_oauth_token.yml
    mode: get
  become: no

- name: Load GitHub OAuth token from YML file
  local_action:
    module: include_vars
    file: /tmp/github_oauth_token.yml

- name: Grab mongo users from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users token from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users

- name: Create the /var/cyhy/scripts/cyhy-feeds/
  file:
    path: /var/cyhy/scripts/cyhy-feeds/
    state: directory
    owner: cyhy
    group: cyhy

- name: Create the /var/cyhy/scripts/cyhy-feeds/extracts
  file:
    path: /var/cyhy/scripts/cyhy-feeds/cyhy_extracts
    state: directory
    owner: cyhy
    group: cyhy

- name: Create /etc/cyhy dir
  file:
    path: /etc/cyhy
    state: directory

- name: Download cyhy extract from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/jsf9k/cyhy-feeds/develop/aws_jobs/cyhy-data-extract.py"
    headers:
      Authorization: "token {{ github_oauth_token }}"
    dest: /var/cyhy/scripts/cyhy-feeds/cyhy-data-extract.py
    mode: 0755
    owner: cyhy
    group: cyhy

- name: Download dmarc extract from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/jsf9k/cyhy-feeds/develop/aws_jobs/dmarc.py"
    headers:
      Authorization: "token {{ github_oauth_token }}"
    dest: /var/cyhy/scripts/cyhy-feeds/dmarc.py
    mode: 0755
    owner: cyhy
    group: cyhy

- name: Grab cyhy extract config file from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: cyhy-data-extract.cfg
    dest: /tmp/cyhy-data-extract.cfg
    mode: get
  become: no

- name: Grab gpg public key from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: ncats_lab_public_gpg.key
    dest: /tmp/ncats_lab_public_gpg.key
    mode: get
  become: no

- name: Grab cyhy private key from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: ncats_lab_private_gpg.key
    dest: /tmp/ncats_lab_private_gpg.key
    mode: get
  become: no

- name: Grab cyhy nsd public key from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: nsd_cyhy_daily_extract_public.key
    dest: /tmp/nsd_cyhy_daily_extract_public.key
    mode: get
  become: no

- name: Grab gpg trust keys from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: gpg_keys.trust
    dest: /tmp/gpg_keys.trust
    mode: get
  become: no

#
# Copy extract config to new instance
#
- name: Copy config file for moe data extractor
  copy:
    src: /tmp/cyhy-data-extract.cfg
    dest: /var/cyhy/scripts/cyhy-feeds/cyhy-data-extract.cfg
    mode: 0644
    owner: cyhy
    group: cyhy

- name: Copy gpg public key for moe data extract
  copy:
    src: /tmp/ncats_lab_public_gpg.key
    dest: /var/cyhy/scripts/cyhy-feeds/ncats_lab_public_gpg.key
    mode: 0644
    owner: cyhy
    group: cyhy

- name: Copy nsd_cyhy_daily public key for moe data extract
  copy:
    src: /tmp/nsd_cyhy_daily_extract_public.key
    dest: /var/cyhy/scripts/cyhy-feeds/nsd_cyhy_daily_extract_public.key
    mode: 0644
    owner: cyhy
    group: cyhy

- name: Copy gpg private key for moe data extract
  copy:
    src: /tmp/ncats_lab_private_gpg.key
    dest: /var/cyhy/scripts/cyhy-feeds/ncats_lab_private_gpg.key
    mode: 0444
    owner: cyhy
    group: cyhy

- name: Copy gpg trust file
  copy:
    src: /tmp/gpg_keys.trust
    dest: /var/cyhy/scripts/cyhy-feeds/gpg_keys.trust
    mode: 0644
    owner: cyhy
    group: cyhy

- name: Create the /var/cyhy/scripts/cyhy-feeds/cyhy_extracts directory
  file:
    path: /var/cyhy/scripts/cyhy-feeds/cyhy_extracts
    state: directory
    owner: cyhy
    group: cyhy

- name: import lab public key
  shell: "gpg2 --trustdb-name /var/cyhy/.gnupg/trustdb.gpg --import /var/cyhy/scripts/cyhy-feeds/ncats_lab_public_gpg.key"
  become_user: cyhy
  vars:
    ansible_ssh_pipelining: yes

- name: import nsd daily public key
  shell: "gpg2 --trustdb-name /var/cyhy/.gnupg/trustdb.gpg --import /var/cyhy/scripts/cyhy-feeds/nsd_cyhy_daily_extract_public.key"
  become_user: cyhy
  vars:
    ansible_ssh_pipelining: yes

- name: import lab private key
  shell: "gpg2 --batch --import /var/cyhy/scripts/cyhy-feeds/ncats_lab_private_gpg.key"
  become_user: cyhy
  vars:
    ansible_ssh_pipelining: yes

- name: Add trust
  shell: "gpg2 --import-ownertrust /var/cyhy/scripts/cyhy-feeds/gpg_keys.trust"
  become_user: cyhy
  vars:
    ansible_ssh_pipelining: yes

- name: Delete nsd public key
  local_action:
    module: file
    path: /tmp/nsd_cyhy_daily_extract_public.key
    state: absent
  become: no

- name: Delete local copy config file for moe data extractor
  local_action:
    module: file
    path: /tmp/cyhy-data-extract.cfg
    state: absent
  become: no

- name: Delete local copy gpg public key for moe data extract
  local_action:
    module: file
    path: /tmp/ncats_lab_public_gpg.key
    state: absent
  become: no

- name: Delete local copy gpg public key for moe data extract
  local_action:
    module: file
    path: /tmp/ncats_lab_private_gpg.key
    state: absent
  become: no

- name: Delete gpg trust file
  local_action:
    module: file
    path: /tmp/gpg_keys.trust
    state: absent
  become: no

- name: Create /etc/cyhy/cyhy.conf with commander credentials
  copy:
    dest: /etc/cyhy/cyhy.conf
    owner: cyhy
    group: cyhy
    mode: 0660
    content: |
      [DEFAULT]
      default-section = production
      database-uri = mongodb://localhost:27017/
      report-key =

      [production]
      database-uri = mongodb://commander:{{ mongo_users.other_users | selectattr("user", "eq", "commander") | map(attribute="password") | first }}@database1:27017/cyhy
      database-name = cyhy

#
# Run  nightly at 0815 (UTC) as cyhy
#
- name: Set up nightly cron job to sync NSD data for moe extract
  cron:
    name: Nightly cyhy extract
    hour: 08
    minute: 15
    user: cyhy
    job: python2.7 /var/cyhy/scripts/cyhy-feeds/cyhy-data-extract.py --section production --aws --config /var/cyhy/scripts/cyhy-feeds/cyhy-data-extract.cfg
