---
# tasks file for mgmt_ops

#
# Create the mgmt_ops user
#
- name: Create the mgmt_ops user
  ansible.builtin.user:
    name: mgmt_ops

# Make sure the /home/mgmt_ops/.ssh directory exists
- name: Create the /home/mgmt_ops/.ssh directory
  ansible.builtin.file:
    path: /home/mgmt_ops/.ssh
    owner: mgmt_ops
    group: mgmt_ops
    mode: 0700
    state: directory

#
# Create the .ssh/authorized_keys file for mgmt_ops
#
- name: Create .ssh/authorized_keys file for mgmt_ops
  ansible.builtin.lineinfile:
    path: /home/mgmt_ops/.ssh/authorized_keys
    line: "{{ lookup('aws_ssm', '/ssh/public_keys/{{ item }}') }}"
    create: yes
    owner: mgmt_ops
    group: mgmt_ops
    mode: 0600
  loop: "{{ ops_users }}"
