---
# tasks file for bod_docker

#
# orchestrator secrets
#
- name: Create a temporary directory to store the orchestrator secrets
  local_action:
    module: file
    path: /tmp/secrets/aws
    state: directory
  become: no

- name: Grab the orchestrator database credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: "orchestrator_secrets/{{ item }}"
    dest: "/tmp/secrets/{{ item }}"
    mode: get
  become: no
  loop:
    - cyhy_read_creds.yml
    - scan_read_creds.yml
    - scan_write_creds.yml

- name: Grab the orchestrator AWS credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: "orchestrator_secrets/aws/{{ item }}"
    dest: "/tmp/secrets/aws/{{ item }}"
    mode: get
  become: no
  loop:
    - config
    - credentials

- name: Copy the orchestrator secrets
  copy:
    src: /tmp/secrets
    dest: /var/cyhy/orchestrator
    owner: admin
    group: admin
    mode: 0750

- name: Delete local copy of orchestrator secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: absent
  become: no


#
# cyhy-mailer secrets
#
- name: Create a temporary directory to store the cyhy-mailer secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: directory
  become: no

- name: Grab the cyhy-mailer database credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: cyhy-mailer_secrets/database_creds.yml
    dest: /tmp/secrets/database_creds.yml
    mode: get
  become: no

- name: Copy the cyhy-mailer secrets
  copy:
    src: /tmp/secrets
    dest: /var/cyhy/cyhy-mailer
    owner: admin
    group: admin
    mode: 0750

- name: Delete local copy of cyhy-mailer secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: absent
  become: no
