---
# tasks file for bod_docker

#
# Load mongo users and passwords into a variable
#
- name: Grab mongo users and passwords from S3
  local_action:
    module: aws_s3
    bucket: ncats-cyhy-secrets
    object: mongo_users.yml
    dest: /tmp/mongo_users.yml
    mode: get
  become: no

- name: Load mongo users and passwords from YML file
  local_action:
    module: include_vars
    file: /tmp/mongo_users.yml
    name: mongo_users
  become: no

#
# orchestrator secrets
#
- name: Create the secrets directories for orchestrator and cyhy-mailer
  file:
    path: "{{ item }}"
    owner: admin
    group: admin
    state: directory
  loop:
    - /var/cyhy/orchestrator/secrets
    - /var/cyhy/cyhy-mailer/secrets

- name: Create the orchestrator credentials file to allow reading the cyhy database
  copy:
    dest: /var/cyhy/orchestrator/secrets/cyhy_read_creds.yml
    owner: admin
    group: admin
    mode: 0440
    content: |
      version: '1'

      database:
        name: cyhy
        uri: mongodb://reporter:{{ mongo_users.other_users | selectattr("user", "eq", "reporter") | map(attribute="password") | first }}@{{ mongo_host }}:27017/cyhy

- name: Create the orchestrator credentials file to allow reading the scan database
  copy:
    dest: /var/cyhy/orchestrator/secrets/scan_read_creds.yml
    owner: admin
    group: admin
    mode: 0440
    content: |
      version: '1'

      database:
        name: scan
        uri: mongodb://scan-reader:{{ mongo_users.other_users | selectattr("user", "eq", "scan-reader") | map(attribute="password") | first }}@{{ mongo_host }}:27017/scan

- name: Create the orchestrator credentials file to allow writing to the scan database
  copy:
    dest: /var/cyhy/orchestrator/secrets/scan_write_creds.yml
    owner: admin
    group: admin
    mode: 0440
    content: |
      version: '1'

      database:
        name: scan
        uri: mongodb://scan-writer:{{ mongo_users.other_users | selectattr("user", "eq", "scan-writer") | map(attribute="password") | first }}@{{ mongo_host }}:27017/scan

- name: Create a temporary directory to store the orchestrator AWS secrets
  local_action:
    module: file
    path: /tmp/secrets/aws
    state: directory
  become: no

- name: Grab the orchestrator AWS credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: "orchestrator_secrets/aws/{{ item }}"
    dest: "/tmp/secrets/aws/{{ item }}"
    mode: get
  become: no
  loop:
    - config
    - credentials

- name: Copy the orchestrator AWS secrets
  copy:
    src: /tmp/secrets/aws
    dest: /var/cyhy/orchestrator/secrets
    owner: admin
    group: admin
    mode: 0750

- name: Delete local copy of orchestrator secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: absent
  become: no


#
# cyhy-mailer secrets
#
# The cyhy-mailer container does not run as root, so the creds files
# need to be globally readable.  docker-compose does allow one to
# specify the uid, gid, and mode of the secrets files, but that only
# works in swarm mode.
#
- name: Copy the cyhy-mailer database credentials
  copy:
    src: /var/cyhy/orchestrator/secrets/cyhy_read_creds.yml
    remote_src: yes
    dest: /var/cyhy/cyhy-mailer/secrets/database_creds.yml
    owner: admin
    group: admin
    mode: 0444

- name: Create a temporary directory to store the cyhy-mailer AWS SMTP credentials
  local_action:
    module: file
    path: /tmp/secrets/smtp
    state: directory
  become: no

- name: Grab the cyhy-mailer AWS SMTP credentials from S3
  local_action:
    module: aws_s3
    bucket: ncats-bod-18-01-secrets
    object: cyhy-mailer_secrets/smtp_creds.yml
    dest: /tmp/secrets/smtp/smtp_creds.yml
    mode: get
  become: no

- name: Copy the cyhy-mailer AWS SMTP credentials
  copy:
    src: /tmp/secrets/smtp/smtp_creds.yml
    dest: /var/cyhy/cyhy-mailer/secrets/smtp_creds.yml
    owner: admin
    group: admin
    mode: 0444

- name: Delete local copy of cyhy-mailer secrets
  local_action:
    module: file
    path: /tmp/secrets
    state: absent
  become: no


#
# Add users to the admin group
#
- name: Load users from YML file
  local_action:
    module: include_vars
    file: ../../../../terraform/scripts/user_ssh_setup.yml
    name: ssh_users
  become: no

- name: Add known users to the docker and admin groups
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  loop: "{{ ssh_users.users | map(attribute='name') | list }}"
