---
# tasks file for bod_docker
- name: Create the /var/cyhy/orchestrator directory
  file:
    path: /var/cyhy/orchestrator
    state: directory
    mode: 0755
    owner: admin
    group: admin

- name: Download and untar the orchestrator tarball
  unarchive:
    src: https://api.github.com/repos/dhs-ncats/orchestrator/tarball/develop
    dest: /var/cyhy/orchestrator
    remote_src: yes
    owner: admin
    group: admin
    extra_opts:
      - "--strip-components=1"

- name: Create the /var/cyhy/cyhy-mailer directory
  file:
    path: /var/cyhy/cyhy-mailer
    state: directory
    mode: 0755
    owner: admin
    group: admin

- name: Download and untar the cyhy-mailer tarball
  unarchive:
    src: https://api.github.com/repos/dhs-ncats/cyhy-mailer/tarball/develop
    dest: /var/cyhy/cyhy-mailer
    remote_src: yes
    owner: admin
    group: admin
    extra_opts:
      - "--strip-components=1"
