---
# tasks file for persist_journald

- name: Configure journald to persist storage
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: ^#Storage=
    state: present
    line: Storage=persistent
  when:
    - ansible_service_mgr == "systemd"
